// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mxegpvlqmolaadlfagup.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im14ZWdwdmxxbW9sYWFkbGZhZ3VwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1MDU5NzYsImV4cCI6MjA2ODA4MTk3Nn0.mOZDS4Z19LXTBgEg5hucWz5HHCOeBeyOuxJG6POuDp0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});